export const MODULES = [
  {
    id: "01",
    title: "El Sistema que Nadie te Explicó",
    tag: "Base",
    color: "red",
    desc: "Antes de tomar cualquier decisión financiera, necesitas entender cómo funciona el sistema. Aquí ponemos todo sobre la mesa — sin tecnicismos y sin letra chica.",
    lessons: [
      { title: "Cómo funciona el dinero y el sistema financiero en Chile", duration: "18 min" },
      { title: "CMF, bancos, cooperativas y financieras — diferencias reales", duration: "22 min" },
      { title: "Cómo leer un contrato bancario y entender el CAE", duration: "25 min" },
      { title: "Tasas de interés: qué significan y cómo te afectan", duration: "20 min" },
      { title: "Los errores financieros más comunes de los chilenos", duration: "15 min" },
    ],
  },
  {
    id: "02",
    title: "Beneficios Sociales que ya Pagaste",
    tag: "Social",
    color: "sky",
    desc: "Hay beneficios que ya te corresponden y que probablemente no estás usando. Este módulo te enseña a identificarlos y pedirlos correctamente.",
    lessons: [
      { title: "Fonasa: tramos, prestaciones y cómo usarlo bien", duration: "20 min" },
      { title: "AFP: cómo leer tu saldo real y qué opciones tienes", duration: "28 min" },
      { title: "BPS: pensiones, subsidios y bonos disponibles", duration: "18 min" },
      { title: "Subsidio habitacional y subsidio al arriendo — cómo postular", duration: "30 min" },
      { title: "Bonos del gobierno: quién puede pedirlos y cuándo", duration: "15 min" },
    ],
  },
  {
    id: "03",
    title: "Finanzas para Emprendedores",
    tag: "Negocio",
    color: "red",
    desc: "Desde cómo crear tu empresa legalmente hasta abrir tu primera cuenta bancaria y empezar a operar con orden.",
    lessons: [
      { title: "Tipos de empresa en Chile: SPA, SpA, SA — cuál elegir", duration: "22 min" },
      { title: "Crear tu empresa paso a paso (SII, Registro Civil, notaría)", duration: "35 min" },
      { title: "Inicio de actividades en el SII — qué es y cómo hacerlo", duration: "20 min" },
      { title: "Abrir cuenta corriente o vista empresarial — qué piden los bancos", duration: "25 min" },
      { title: "BancoEstado, BCI, Santander — opciones para empresas nuevas", duration: "18 min" },
      { title: "Régimen tributario: Pro PyME vs General — cuál te conviene", duration: "28 min" },
      { title: "IVA, PPM y declaración de renta explicados simple", duration: "32 min" },
      { title: "Boletas de honorarios vs facturas — cuándo usar cada una", duration: "20 min" },
      { title: "Separar finanzas personales de las del negocio desde el día uno", duration: "15 min" },
    ],
  },
  {
    id: "04",
    title: "Financiamiento & Beneficios PyME",
    tag: "Crédito",
    color: "sky",
    desc: "El Estado tiene herramientas para financiar tu negocio que la mayoría no conoce. Aquí aprendes a usarlas.",
    lessons: [
      { title: "Capital Semilla SERCOTEC — cómo postular paso a paso", duration: "30 min" },
      { title: "Corfo: líneas de crédito y garantías Fogape", duration: "25 min" },
      { title: "BancoEstado Microempresa: cuenta y créditos disponibles", duration: "20 min" },
      { title: "Factoring y leasing como herramientas de capital de trabajo", duration: "22 min" },
      { title: "Errores más comunes al buscar financiamiento bancario", duration: "18 min" },
    ],
  },
  {
    id: "05",
    title: "Deuda Inteligente & Crédito",
    tag: "Deuda",
    color: "red",
    desc: "No toda deuda es mala. La clave está en saber cuándo endeudarse, cómo negociar y cómo salir cuando algo sale mal.",
    lessons: [
      { title: "Deuda buena vs deuda mala — cuándo sirve endeudarse", duration: "20 min" },
      { title: "Cómo negociar con un banco de verdad", duration: "28 min" },
      { title: "DICOM y Equifax — cómo funciona tu historial crediticio", duration: "22 min" },
      { title: "Repactación y renegociación de deudas sin perder el control", duration: "25 min" },
      { title: "Cuándo tiene sentido pedir crédito para crecer", duration: "18 min" },
    ],
  },
  {
    id: "06",
    title: "Construir Patrimonio en Chile",
    tag: "Inversión",
    color: "sky",
    desc: "Ahorrar no es lo mismo que construir patrimonio. Este módulo te muestra cómo pensar el dinero a largo plazo en el contexto chileno.",
    lessons: [
      { title: "APV: ahorro previsional voluntario y sus beneficios tributarios", duration: "28 min" },
      { title: "Inversiones inmobiliarias y DFL2 — lo que hay que saber", duration: "30 min" },
      { title: "Acciones y ETFs desde Chile — cómo empezar sin complicarse", duration: "25 min" },
      { title: "Interés compuesto aplicado a la realidad chilena", duration: "20 min" },
      { title: "Cómo Roberto construyó patrimonio desde sus negocios reales", duration: "35 min" },
    ],
  },
];
